ui:
  defaults:
    colorMode: ''
    accentHue: 271
    accentSaturation: 91
    fontFamily: google-sans
    fontSize: normal
    editorMode: normal
    editorKeymap: default
    editorStickyToolbar: true
    editorFixedHeight: 0
    adminLanguage: en-US
    pagesPerPage: 20
    pagesViewMode: tree
    usersViewMode: cards
    groupsViewMode: cards
    pluginsViewMode: cards
    themesViewMode: cards
    flexAfterSave: ''
  settings:
    autoSaveEnabled: false
    autoSaveToolbarUndo: true
    autoSaveBatchWindowMs: 0
    collabEnabled: true
    menubarLinks: {  }
