title: Seite
icon: page

columns:
  - width: 2/3
    sections:
      inhalt:
        type: fields
        fields:
          intro:
            label: Kurztext / Lead
            type: textarea
            size: small
          text:
            label: Inhalt
            type: textarea
            size: large

  - width: 1/3
    sections:
      seitlich:
        type: fields
        fields:
          kopfHintergrund:
            label: Hintergrundbild des Kopfbereichs
            type: files
            query: page.images
            uploads: true
            max: 1
            layout: cards
            help: Wird stark weichgezeichnet hinter dem Titel angezeigt.
      dateien:
        type: files
        label: Dateien zum Download
        template: rangliste
        layout: list
        image: false
